function firstText(selectors,root=document){for(const s of selectors){const t=root.querySelector(s)?.innerText?.trim();if(t)return t}return''}
function clean(v,max=5000){return String(v||'').replace(/\s+/g,' ').trim().slice(0,max)}
function outbound(value){try{const u=new URL(value,location.href);if(!/(^|\.)linkedin\.com$/i.test(u.hostname))return /^https?:$/.test(u.protocol)?u.href:null;for(const key of['url','target','dest','destination']){const raw=u.searchParams.get(key);if(raw){const n=new URL(raw);if(/^https?:$/.test(n.protocol))return n.href}}}catch{}return null}
function activeMessageRoot(){return document.querySelector('.msg-overlay-conversation-bubble--is-active')||document.querySelector('.msg-overlay-conversation-bubble')||document.querySelector('.msg-thread')||document.querySelector('main .msg-s-message-list-container')}
function detectPageType(){const p=location.pathname.toLowerCase();if(p.startsWith('/messaging/'))return'messaging';if(p.startsWith('/company/')||p.includes('/sales/company/')||document.querySelector('.org-top-card,.org-top-card-summary,.org-page-details-module'))return'company';if(p.startsWith('/in/')||p.includes('/sales/lead/')||document.querySelector('.pv-top-card,.profile-topcard'))return'profile';return'unsupported'}
function companyRoot(){return document.querySelector('.org-top-card')||document.querySelector('.org-top-card-summary')||document.querySelector('main')}
function aboutRoot(){const direct=document.querySelector('.org-about-module,.org-page-details-module,[data-test-id="about-us"]');if(direct)return direct;return[...document.querySelectorAll('main section')].find(s=>/^about\b/i.test(firstText(['h2','h3'],s)))||null}
function companyIdentity(){const root=companyRoot(),top=clean(root?.innerText,2500),name=firstText(['h1','.org-top-card-summary__title','.org-top-card-primary-content__title'],root||document);const descriptor=firstText(['.org-top-card-summary__tagline','.org-top-card-summary-info-list','.org-top-card-primary-content__tagline'],root||document);const lines=top.split(/\n+/).map(clean).filter(Boolean);const metadata=lines.filter(x=>x!==name&&!/^(follow|message|home|about|posts|jobs|people)$/i.test(x)).slice(0,8);return{name,descriptor,metadata,location:metadata.find(x=>/\b(vietnam|viet nam|hanoi|ha noi|da nang|ho chi minh|united states|arizona|singapore|europe)\b/i.test(x))||'',industry:metadata.find(x=>/services|consulting|software|automation|technology|education|training|manufacturing|security/i.test(x))||''}}
function strictCompanyLinks(){const roots=[companyRoot(),aboutRoot()].filter(Boolean),preferred=[];for(const root of roots){for(const a of root.querySelectorAll('a[href]')){const label=clean(`${a.innerText} ${a.getAttribute('aria-label')||''} ${a.getAttribute('data-control-name')||''}`,300);if(!/website|company site|visit site|external|homepage/i.test(label)&&!a.matches('[data-control-name*="website"],[aria-label*="website" i]'))continue;const url=outbound(a.href);if(url)preferred.push(url)}}return[...new Set(preferred)].slice(0,4)}
function captureThread(){const root=activeMessageRoot()||(location.pathname.startsWith('/messaging/')?(document.querySelector('main')||document):null);if(!root)return[];let nodes=[...root.querySelectorAll('.msg-s-message-list__event,.msg-s-event-listitem,[data-view-name="message-list-item"],li.msg-s-message-list__event')];return nodes.map(n=>({sender:firstText(['.msg-s-message-group__name','.msg-s-event-listitem__name','[data-anonymize="person-name"]','h3'],n),text:firstText(['.msg-s-event-listitem__body','.msg-s-message-group__messages','.msg-s-event-listitem__message-bubble','p'],n),timestamp:firstText(['time','.msg-s-message-group__timestamp','.msg-s-event-listitem__time-heading'],n)})).filter(x=>x.text).filter((x,i,a)=>i===0||x.text!==a[i-1].text).slice(-80)}
function capture(){const type=detectPageType(),thread=captureThread(),identity=type==='company'?companyIdentity():{},about=type==='company'?clean(aboutRoot()?.innerText,6000):'',links=type==='company'?strictCompanyLinks():[];const main=document.querySelector('main')||document.querySelector('[role="main"]')||document.body;return{page:{type,url:location.href,personName:type==='profile'?firstText(['main h1','h1.text-heading-xlarge','.profile-topcard-person-entity__name']):'',personHeadline:type==='profile'?firstText(['main .text-body-medium','.pv-text-details__left-panel .text-body-medium','.profile-topcard__summary-position-title']):'',companyName:identity.name||firstText(['a[href*="/company/"] span','a[href*="/sales/company/"] span']),companyIdentity:identity,companyAbout:about,companyWebsite:links[0]||'',externalLinks:links,visibleText:type==='company'?clean(JSON.stringify({identity,about}),9000):clean(main.innerText,9000),hasVisibleThread:thread.length>0},thread}}
chrome.runtime.onMessage.addListener((m,_s,send)=>{if(m?.type==='DRIX_CAPTURE_CONTEXT')send(capture())});
