function firstText(selectors,root=document){for(const s of selectors){const t=root.querySelector(s)?.innerText?.trim();if(t)return t}return''}
function clean(v,max=5000){return String(v||'').replace(/\s+/g,' ').trim().slice(0,max)}
function lines(v,max=8000){return String(v||'').slice(0,max).split(/\r?\n/).map(x=>clean(x,500)).filter(Boolean)}
function outbound(value){try{const u=new URL(value,location.href);if(!/(^|\.)linkedin\.com$/i.test(u.hostname))return /^https?:$/.test(u.protocol)?u.href:null;for(const key of['url','target','dest','destination']){const raw=u.searchParams.get(key);if(raw){const n=new URL(raw);if(/^https?:$/.test(n.protocol))return n.href}}}catch{}return null}
function activeMessageRoot(){return document.querySelector('.msg-overlay-conversation-bubble--is-active')||document.querySelector('.msg-overlay-conversation-bubble')||document.querySelector('.msg-thread')||document.querySelector('main .msg-s-message-list-container')}
function detectPageType(){const p=location.pathname.toLowerCase();if(p.startsWith('/messaging/'))return'messaging';if(p.startsWith('/company/')||p.includes('/sales/company/')||document.querySelector('.org-top-card,.org-top-card-summary,.org-page-details-module'))return'company';if(p.startsWith('/in/')||p.includes('/sales/lead/')||document.querySelector('.pv-top-card,.profile-topcard'))return'profile';return'unsupported'}
function companyRoot(){return document.querySelector('.org-top-card')||document.querySelector('.org-top-card-summary')||document.querySelector('[data-test-id="about-us__container"]')?.closest('main')||document.querySelector('main')}
function aboutRoot(){const direct=document.querySelector('.org-about-module,.org-page-details-module,[data-test-id="about-us"],[data-test-id="about-us__container"]');if(direct)return direct;return[...document.querySelectorAll('main section')].find(s=>/^about\b/i.test(firstText(['h2','h3'],s)))||null}
function titleCompanyName(){return clean(document.title.replace(/^\(\d+\)\s*/,'').replace(/\s*\|\s*LinkedIn.*$/i,'').replace(/:\s*(overview|about|life|jobs|posts).*$/i,''),300)}
function slugCompanyName(){const m=location.pathname.match(/\/(?:company|sales\/company)\/([^/?#]+)/i);return m?clean(decodeURIComponent(m[1]).replace(/[-_]+/g,' '),300):''}
function looksGenericName(v){return !v||/^(it services( and| &) consulting|software development|business consulting|technology, information and internet|staffing and recruiting|advertising services|education|higher education)$/i.test(clean(v,300))}
function extractFacts(raw){const text=clean(raw,12000),take=re=>text.match(re)?.[0]||'';return{employeeRange:take(/\b\d[\d,.]*\s*[-–]\s*\d[\d,.]*\s+employees\b/i),employeeClaim:take(/\b(?:over|more than|team of)\s+\d[\d,.+]*\s+employees\b/i),employeeProfiles:take(/\b(?:see|view)\s+(?:all\s+)?\d[\d,.+]*\s+employees\b/i),followers:take(/\b\d[\d,.]*\s+followers\b/i),founded:take(/\bfounded\s+(?:in\s+)?\d{4}\b/i)}}
function companyIdentity(){const root=companyRoot(),raw=root?.innerText||'',row=lines(raw),domName=firstText(['h1','[data-test-id="org-name"]','.org-top-card-summary__title','.org-top-card-primary-content__title'],root||document),fromTitle=titleCompanyName(),name=!looksGenericName(fromTitle)?fromTitle:!looksGenericName(domName)?clean(domName,300):slugCompanyName(),descriptor=firstText(['.org-top-card-summary__tagline','.org-top-card-primary-content__tagline','[data-test-id="org-tagline"]'],root||document),metadata=row.filter(x=>x!==name&&!/^(follow|message|home|about|posts|jobs|people|overview)$/i.test(x)).slice(0,18),facts=extractFacts(raw);return{name,descriptor,metadata,facts,location:metadata.find(x=>/\b(vietnam|viet nam|hanoi|ha noi|da nang|ho chi minh|united states|arizona|singapore|sweden|stockholm|europe)\b/i.test(x))||'',industry:metadata.find(x=>/services|consulting|software|automation|technology|education|training|manufacturing|security/i.test(x))||''}}
function strictCompanyLinks(){const out=[],about=aboutRoot(),top=companyRoot();for(const root of[about,top].filter(Boolean)){for(const a of root.querySelectorAll('a[href]')){const label=clean(`${a.innerText} ${a.getAttribute('aria-label')||''} ${a.getAttribute('data-control-name')||''}`,300),url=outbound(a.href);if(!url)continue;if(root===about||/website|company site|visit site|external|homepage/i.test(label)||a.matches('[data-control-name*="website"],[aria-label*="website" i]'))out.push(url)}}return[...new Set(out)].slice(0,6)}
function readMessages(root){if(!root)return[];const nodes=[...root.querySelectorAll('.msg-s-message-list__event,.msg-s-event-listitem,[data-view-name="message-list-item"],li.msg-s-message-list__event')];return nodes.map(n=>({sender:firstText(['.msg-s-message-group__name','.msg-s-event-listitem__name','[data-anonymize="person-name"]','h3'],n),text:firstText(['.msg-s-event-listitem__body','.msg-s-message-group__messages','.msg-s-event-listitem__message-bubble','p'],n),timestamp:firstText(['time','.msg-s-message-group__timestamp','.msg-s-event-listitem__time-heading'],n)})).filter(x=>x.text)}
function messageKey(x){return`${x.sender}|${x.timestamp}|${x.text}`}function dedupe(items){const seen=new Set;return items.filter(x=>{const k=messageKey(x);if(seen.has(k))return false;seen.add(k);return true})}
function captureThread(){return dedupe(readMessages(activeMessageRoot()||(location.pathname.startsWith('/messaging/')?(document.querySelector('main')||document):null))).slice(-80)}
function findScroller(root){const candidates=[...root.querySelectorAll('.msg-s-message-list-container,.msg-s-message-list-content,[class*="message-list"],[class*="scroll"]'),root].filter(Boolean);return candidates.find(x=>x.scrollHeight>x.clientHeight+20)||candidates[0]}
async function loadFullThread(){const root=activeMessageRoot()||(location.pathname.startsWith('/messaging/')?(document.querySelector('main')||document):null);if(!root)return{messages:[],meta:{reachedStart:false,truncated:false,iterations:0}};const scroller=findScroller(root);if(!scroller)return{messages:captureThread(),meta:{reachedStart:false,truncated:false,iterations:0}};const distanceFromBottom=scroller.scrollHeight-scroller.scrollTop,MAX_MESSAGES=250,MAX_ITERATIONS=30;let all=[],stagnant=0,previousHeight=-1,iterations=0,reachedStart=false;for(;iterations<MAX_ITERATIONS&&all.length<MAX_MESSAGES;iterations++){all=dedupe([...readMessages(root),...all]);const older=[...root.querySelectorAll('button,a')].find(x=>/load older|show previous|see previous|earlier messages/i.test(x.innerText||''));if(older)older.click();const beforeCount=all.length,beforeHeight=scroller.scrollHeight;scroller.scrollTop=0;await new Promise(r=>setTimeout(r,700));all=dedupe([...readMessages(root),...all]);const unchanged=all.length===beforeCount&&scroller.scrollHeight===beforeHeight&&previousHeight===beforeHeight;stagnant=unchanged?stagnant+1:0;previousHeight=scroller.scrollHeight;if(stagnant>=3){reachedStart=true;break}}all=dedupe([...readMessages(root),...all]).slice(-MAX_MESSAGES);scroller.scrollTop=Math.max(0,scroller.scrollHeight-distanceFromBottom);return{messages:all,meta:{reachedStart,truncated:all.length>=MAX_MESSAGES||iterations>=MAX_ITERATIONS,iterations}}}
function captureBase(thread,threadMeta){const type=detectPageType(),identity=type==='company'?companyIdentity():{},about=type==='company'?clean(aboutRoot()?.innerText,8000):'',links=type==='company'?strictCompanyLinks():[],main=document.querySelector('main')||document.querySelector('[role="main"]')||document.body,topText=type==='company'?clean(companyRoot()?.innerText,7000):'';return{page:{type,url:location.href,pageTitle:document.title,personName:type==='profile'?firstText(['main h1','h1.text-heading-xlarge','.profile-topcard-person-entity__name']):'',personHeadline:type==='profile'?firstText(['main .text-body-medium','.pv-text-details__left-panel .text-body-medium','.profile-topcard__summary-position-title']):'',companyName:identity.name,companyIdentity:identity,companyAbout:about,companyWebsite:links[0]||'',externalLinks:links,visibleText:type==='company'?clean(JSON.stringify({identity,about,topText}),16000):clean(main.innerText,9000),hasVisibleThread:thread.length>0},thread,threadMeta:threadMeta||{loadedMessages:thread.length,reachedStart:false,truncated:false}}}
function capture(){const thread=captureThread();return captureBase(thread,{loadedMessages:thread.length,reachedStart:false,truncated:false})}
chrome.runtime.onMessage.addListener((m,_s,send)=>{if(m?.type==='DRIX_CAPTURE_CONTEXT'){send(capture());return false}if(m?.type==='DRIX_CAPTURE_FULL_THREAD'){loadFullThread().then(({messages,meta})=>send(captureBase(messages,{...meta,loadedMessages:messages.length}))).catch(e=>send({error:e.message}));return true}return false});
