const cheerio=require('cheerio');
const BLOCKED=['linkedin.com','facebook.com','instagram.com','x.com','twitter.com','youtube.com','crunchbase.com','bloomberg.com','zoominfo.com','glassdoor.com','indeed.com','wikipedia.org','yelp.com','wsj.com'];
const GENERIC=/^(it services(?: and| &)?(?: it)? consulting|software development|business consulting|technology, information and internet|staffing and recruiting|advertising services|education|higher education)$/i;
function httpUrl(v){try{const u=new URL(v);return['http:','https:'].includes(u.protocol)?u.href:null}catch{return null}}
function unredirect(v){const url=httpUrl(v);if(!url)return null;const u=new URL(url);if(!/(^|\.)linkedin\.com$/i.test(u.hostname))return url;for(const k of['url','target','dest','destination']){const n=httpUrl(u.searchParams.get(k));if(n)return n}return null}
function allowed(v){const url=unredirect(v)||httpUrl(v);if(!url)return null;const h=new URL(url).hostname.replace(/^www\./,'').toLowerCase();return BLOCKED.some(x=>h===x||h.endsWith('.'+x))?null:url}
function clean(v,max=20000){return String(v||'').replace(/\s+/g,' ').trim().slice(0,max)}
function slugName(url){try{const m=new URL(url).pathname.match(/\/(?:company|sales\/company)\/([^/]+)/i);return m?decodeURIComponent(m[1]).replace(/[-_]+/g,' ').trim():''}catch{return''}}
function titleName(v){return clean(v).replace(/^\(\d+\)\s*/,'').replace(/\s*\|\s*LinkedIn.*$/i,'').replace(/:\s*(overview|about|life|jobs|posts).*$/i,'')}
function effectiveCompanyName(page={}){const supplied=clean(page.companyName),title=titleName(page.pageTitle);if(title&&!GENERIC.test(title))return title;if(supplied&&!GENERIC.test(supplied))return supplied;return slugName(page.url)||supplied||title}
function tokens(v){return clean(v).toLowerCase().replace(/\b(limited|ltd|llc|inc|corp|corporation|company|co|group|holdings|plc|gmbh|the|services|consulting)\b/g,' ').replace(/[^a-z0-9]+/g,' ').trim().split(/\s+/).filter(x=>x.length>2)}
function pageContext(page={}){const id=page.companyIdentity||{};return clean([page.companyName,page.pageTitle,id.name,id.descriptor,id.industry,id.location,JSON.stringify(id.metadata||[]),JSON.stringify(id.facts||{}),page.companyAbout,page.visibleText].join(' '))}
function categories(text){const t=clean(text).toLowerCase();return{technology:/\b(software|saas|devops|digital development|web development|mobile development|it services|information technology|technology consulting|automation|managed services)\b/.test(t),automotive:/\b(automotive|oil filters?|air filters?|fuel filters?|engine oil|motor oil|vehicles?|cars?|everyday drivers?|miles)\b/.test(t),education:/\b(school|college|university|vocational|students?|training programs?|postsecondary)\b/.test(t),vietnam:/\b(vietnam|viet nam|ho chi minh|hanoi|ha noi|da nang)\b/.test(t),sweden:/\b(sweden|swedish|stockholm)\b/.test(t),usa:/\b(united states|michigan|kentucky|ohio|arizona|usa|u\.s\.)\b/.test(t)} }
function semanticCandidateScore(page,candidateText){const target=categories(pageContext(page)),candidate=categories(candidateText);let score=0,conflict='';if(target.technology&&candidate.automotive&&!candidate.technology){score-=120;conflict='automotive website conflicts with IT/software target'}if(target.automotive&&candidate.technology&&!candidate.automotive){score-=120;conflict='technology website conflicts with automotive target'}if(target.education&&!candidate.education&&(candidate.automotive||candidate.technology)){score-=90;conflict='candidate industry conflicts with education target'}if(target.technology&&candidate.technology)score+=35;if(target.automotive&&candidate.automotive)score+=35;if(target.education&&candidate.education)score+=35;if(target.vietnam&&candidate.vietnam)score+=25;if(target.sweden&&candidate.sweden)score+=15;if(target.vietnam&&candidate.usa&&!candidate.vietnam)score-=25;return{score,conflict,target,candidate}}
function scoreCandidate(url,pageOrName={},title='',snippet=''){const page=typeof pageOrName==='string'?{companyName:pageOrName}:pageOrName,companyName=effectiveCompanyName(page),host=new URL(url).hostname.replace(/^www\./,'').toLowerCase(),hay=`${title} ${snippet}`.toLowerCase();let score=0;for(const t of tokens(companyName)){if(host.includes(t))score+=8;if(hay.includes(t))score+=2}for(const t of tokens(`${page.companyIdentity?.location||''} ${page.companyIdentity?.industry||''}`)){if(hay.includes(t))score+=2}if(/official|homepage/i.test(title))score+=2;if(/\.edu($|\/)/i.test(url)&&!/education|school|institute|training/i.test(page.companyIdentity?.industry||''))score-=12;return score+semanticCandidateScore(page,hay).score}
async function fetchCandidateText(url){const r=await fetch(url,{redirect:'follow',signal:AbortSignal.timeout(15000),headers:{'User-Agent':'Mozilla/5.0 (compatible; DRiXResearch/1.2)'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const $=cheerio.load(await r.text());$('script,style,noscript,svg').remove();return{url:r.url||url,title:clean($('title').first().text(),300),text:clean($('body').text(),18000)}}
async function verifyCandidate(candidate,page,{supplied=false}={}){const url=allowed(candidate?.url||candidate);if(!url)return{accepted:false,score:-999,reason:'blocked URL'};const hint=clean(`${candidate?.title||''} ${candidate?.snippet||''}`);let fetched=null;try{fetched=await fetchCandidateText(url)}catch(e){if(!supplied)return{accepted:false,score:-999,reason:`candidate website unavailable: ${e.message}`}}const evidence=clean(`${hint} ${fetched?.title||''} ${fetched?.text||''}`),semantic=semanticCandidateScore(page,evidence),score=scoreCandidate(fetched?.url||url,page,candidate?.title||fetched?.title||'',`${candidate?.snippet||''} ${fetched?.text||''}`);if(semantic.conflict)return{accepted:false,score,reason:semantic.conflict,url:fetched?.url||url};return{accepted:score>=12||supplied&&score>=8,score,reason:score>=12?'identity signals agree':'insufficient identity agreement',url:fetched?.url||url}}
async function searchCandidates(page){const companyName=effectiveCompanyName(page);if(!companyName)return[];const id=page.companyIdentity||{},geography=clean(id.location).match(/vietnam|viet nam|singapore|sweden|stockholm|hanoi|ha noi|da nang|ho chi minh|united states|arizona/i)?.[0]||'',industry=clean(id.industry).split(/\s+/).filter(x=>/software|technology|consulting|services|automation|manufacturing|education/i.test(x)).slice(0,3).join(' '),q=encodeURIComponent(`"${companyName}" ${geography} ${industry} official website`),r=await fetch(`https://html.duckduckgo.com/html/?q=${q}`,{signal:AbortSignal.timeout(15000),headers:{'User-Agent':'Mozilla/5.0 (compatible; DRiXResearch/1.2)'}});if(!r.ok)throw new Error(`Website discovery returned HTTP ${r.status}`);const $=cheerio.load(await r.text()),out=[];$('.result').each((_i,node)=>{const a=$(node).find('.result__a,a.result-link').first(),raw=a.attr('href');let value=raw;try{const u=new URL(raw,'https://duckduckgo.com');value=u.searchParams.get('uddg')||u.href}catch{}const url=allowed(value),title=a.text().trim(),snippet=$(node).find('.result__snippet').text().trim();if(url&&!out.some(x=>new URL(x.url).hostname===new URL(url).hostname))out.push({url,title,snippet,baseScore:scoreCandidate(url,page,title,snippet)})});return out.sort((a,b)=>b.baseScore-a.baseScore).slice(0,6)}
async function discoverOfficialWebsite(page){const candidates=await searchCandidates(page),checked=await Promise.all(candidates.map(x=>verifyCandidate(x,page)));checked.sort((a,b)=>b.score-a.score);return checked.find(x=>x.accepted)?.url||null}
async function ensureCompanyWebsite(page){const companyName=effectiveCompanyName(page),strict=[page?.companyWebsite,...(page?.externalLinks||[])].map(allowed).filter(Boolean);for(const url of strict){const checked=await verifyCandidate({url},page,{supplied:true});if(checked.accepted)return{url:checked.url,supplied:true,companyName,verification:checked.reason};console.warn(`[copilot] rejected supplied company URL ${url}: ${checked.reason}`)}try{const url=await discoverOfficialWebsite({...page,companyName});return{url,discovered:!!url,companyName,verification:url?'industry and geography verified':'no verified candidate'}}catch(e){console.warn('[copilot] company URL discovery:',e.message);return{url:null,companyName,verification:e.message}}}
module.exports={httpUrl,unredirect,allowed,slugName,titleName,effectiveCompanyName,categories,semanticCandidateScore,scoreCandidate,fetchCandidateText,verifyCandidate,searchCandidates,discoverOfficialWebsite,ensureCompanyWebsite};
